### ISSUE TITLE
Unable to use C# 12 features

### ISSUE THREAD

**Issue by j0of** [razzmatazz/csharp-language-server#150]
Hi there, I have run into a similar issue where I can't use some .NET 8 (or rather, C# 12) features within my project. For example, using primary constructors will give the error:
```
The feature 'primary constructors' is currently in Preview and *unsupported*. To use Preview features, use the 'preview' language version.
```
I'm using Neovim with mason, mason-lspconfig, and nvim-lspconfig.

**Comment by razzmatazz** [comment]
Did you try to build csharp-ls from source -- `main` has a lot of code changed since `0.11.0`, including a bump for roslyn imports (microsoft.codeanalysis) to 4.9.2:
- https://www.nuget.org/packages/Microsoft.CodeAnalysis/

I will release a new version soon but trying to stabilize/test the code first.

**Comment by razzmatazz** [comment]
Related PR by @arussellk: https://github.com/razzmatazz/csharp-language-server/pull/141

**Comment by razzmatazz** [comment]
0.12.0 has been released which should include a fix

**Comment by j0of** [comment]
New version fixed it. Thanks a lot! 😁
